include:
  - board: dao_left
  - board: dao_right

  - board: seeeduino_xiao_ble 
    shield: dao_dongle prospector_adapter

  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
