include:
  - board: dao_left
  - board: dao_right

  - board: seeeduino_xiao_ble
    shield: dao_dongle prospector_adapter

  # Сброс настроек/BLE-бондов для половинок (нужен при смене роли).
  - board: dao_left
    shield: settings_reset
  - board: dao_right
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: settings_reset
